# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gamewindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd



class Ui_MainWindow1(object):
    def setup(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1128, 867)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Background = QtWidgets.QLabel(self.centralwidget)
        self.Background.setGeometry(QtCore.QRect(0, 0, 1131, 511))
        self.Background.setText("")
        self.Background.setPixmap(QtGui.QPixmap("img/space1.jpg"))
        self.Background.setScaledContents(True)
        self.Background.setObjectName("Background")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 510, 1131, 361))
        self.groupBox.setObjectName("groupBox")
        self.MetaBack = QtWidgets.QLabel(self.groupBox)
        self.MetaBack.setGeometry(QtCore.QRect(-10, -10, 1141, 371))
        self.MetaBack.setAutoFillBackground(False)
        self.MetaBack.setText("")
        self.MetaBack.setPixmap(QtGui.QPixmap("img/metal.jpg"))
        self.MetaBack.setScaledContents(True)
        self.MetaBack.setObjectName("MetaBack")
        self.boton1 = QtWidgets.QPushButton(self.groupBox)
        self.boton1.setGeometry(QtCore.QRect(30, 140, 421, 101))
        self.boton1.setObjectName("boton1")
        self.boton1.clicked.connect(self.A_clicked)
        self.boton3 = QtWidgets.QPushButton(self.groupBox)
        self.boton3.setGeometry(QtCore.QRect(630, 140, 421, 101))
        self.boton3.setObjectName("boton3")
        self.boton3.clicked.connect(self.C_clicked)
        self.boton2 = QtWidgets.QPushButton(self.groupBox)
        self.boton2.setGeometry(QtCore.QRect(30, 250, 421, 101))
        self.boton2.setObjectName("boton2")
        self.boton2.clicked.connect(self.B_clicked)
        self.boton4 = QtWidgets.QPushButton(self.groupBox)
        self.boton4.setGeometry(QtCore.QRect(630, 250, 421, 101))
        self.boton4.setObjectName("boton4")
        self.boton4.clicked.connect(self.D_clicked)
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(10, 0, 1091, 141))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.labelpregunta = QtWidgets.QLabel(self.frame)
        self.labelpregunta.setGeometry(QtCore.QRect(60, 30, 971, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.labelpregunta.setPalette(palette)
        self.labelpregunta.setAlignment(QtCore.Qt.AlignCenter)
        self.labelpregunta.setObjectName("labelpregunta")
        self.questionbackground = QtWidgets.QLabel(self.frame)
        self.questionbackground.setGeometry(QtCore.QRect(0, 0, 1091, 141))
        self.questionbackground.setText("")
        self.questionbackground.setPixmap(QtGui.QPixmap("img/metalscreen.png"))
        self.questionbackground.setScaledContents(True)
        self.questionbackground.setObjectName("questionbackground")
        self.questionbackground.raise_()
        self.labelpregunta.raise_()
        self.Ship = QtWidgets.QLabel(self.centralwidget)
        self.Ship.setGeometry(QtCore.QRect(30, 270, 161, 91))
        self.Ship.setText("")
        self.Ship.setPixmap(QtGui.QPixmap("img/SpShip.png"))
        self.Ship.setScaledContents(True)
        self.Ship.setObjectName("Ship")
        self.hearticon = QtWidgets.QLabel(self.centralwidget)
        self.hearticon.setGeometry(QtCore.QRect(10, 20, 51, 41))
        self.hearticon.setText("")
        self.hearticon.setPixmap(QtGui.QPixmap("img/Heart.png"))
        self.hearticon.setScaledContents(True)
        self.hearticon.setObjectName("hearticon")
        self.numliveslabel = QtWidgets.QLabel(self.centralwidget)
        self.numliveslabel.setGeometry(QtCore.QRect(60, 20, 31, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.numliveslabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.numliveslabel.setFont(font)
        self.numliveslabel.setAutoFillBackground(False)
        self.numliveslabel.setScaledContents(True)
        self.numliveslabel.setObjectName("numliveslabel")
        self.Enemy = QtWidgets.QLabel(self.centralwidget)
        self.Enemy.setGeometry(QtCore.QRect(800, 240, 231, 161))
        self.Enemy.setText("")
        self.Enemy.setPixmap(QtGui.QPixmap("img/enemy.png"))
        self.Enemy.setScaledContents(True)
        self.Enemy.setObjectName("Enemy")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.boton1.setText(_translate("MainWindow", "A"))
        self.boton2.setText(_translate("MainWindow", "B"))
        self.boton3.setText(_translate("MainWindow", "C"))
        self.boton4.setText(_translate("MainWindow", "D"))
        self.labelpregunta.setText(_translate("MainWindow", "Pregunta"))
        self.numliveslabel.setText(_translate("MainWindow", "x3"))
    
    def A_clicked(self):
        answer = "a"
    def B_clicked(self):
        answer = "b"
    def C_clicked(self):
        answer = "c"
    def D_clicked(self):
        answer = "d"
    
def play(self):
    import numpy as np
    archivopreg = 'QyA.xlsx'
    preguntas = pd.read_excel(archivopreg)
    lives = 3
    livestr = str(lives)
    score = 0
    used = []
    while lives > 0:
        num = np.random.randint(0,5)
        while num not in used:
            preg= preguntas['Pregunta'][num]
            respa=preguntas['A'][num]
            respb=preguntas['B'][num]
            respc=preguntas['C'][num]
            respd=preguntas['D'][num]
            respcorrect= preguntas['Correcta'][num]
            used.append(num)
            retranslateUi(respa,respb,respc,respd,preg,livestr)
            if Ui_MainWindow1.answer == respcorrect.lower():
                score += 100
            else:
                lives -= 1
                livestr = str(lives)
                retranslateUi(respa,respb,respc,respd,preg,livestr)
                

def retranslateUi(respa,respb,respc,respd,preg,livestr):
    _translate = QtCore.QCoreApplication.translate
    Ui_MainWindow1.boton1.setText(_translate("MainWindow", respa))
    Ui_MainWindow1.boton2.setText(_translate("MainWindow", respb))
    Ui_MainWindow1.boton3.setText(_translate("MainWindow", respc))
    Ui_MainWindow1.boton4.setText(_translate("MainWindow", respd))
    Ui_MainWindow1.labelpregunta.setText(_translate("MainWindow", preg))
    Ui_MainWindow1.numliveslabel.setText(_translate("MainWindow", "x"+ livestr))
  


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow1()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


