# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#from gamewindow import *
import numpy as np
from rbgame import *
import rbgame


class Ui_MainWindow(object):
    
    def gamestart(self):
        self.window = QtWidgets.QMainWindow()
        self.ui= Ui_MainWindow1()
        self.ui.setup(self.window)
        self.window.show()
        self.ui.play()
        

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1044, 836)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Background = QtWidgets.QLabel(self.centralwidget)
        self.Background.setGeometry(QtCore.QRect(-6, -5, 1051, 841))
        self.Background.setText("")
        self.Background.setPixmap(QtGui.QPixmap("img/space9.gif"))
        self.Background.setScaledContents(True)
        self.Background.setObjectName("Background")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 30, 971, 781))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(160, 70, 661, 221))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/Title3.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.BotonJugar = QtWidgets.QPushButton(self.frame)
        self.BotonJugar.setGeometry(QtCore.QRect(380, 350, 201, 81))
        self.BotonJugar.setObjectName("BotonJugar")
        self.BotonJugar.clicked.connect(self.gamestart)
        self.BotonPuntuacion = QtWidgets.QPushButton(self.frame)
        self.BotonPuntuacion.setGeometry(QtCore.QRect(380, 480, 201, 71))
        self.BotonPuntuacion.setObjectName("BotonPuntuacion")
        self.botonopciones = QtWidgets.QPushButton(self.frame)
        self.botonopciones.setGeometry(QtCore.QRect(430, 650, 93, 28))
        self.botonopciones.setObjectName("botonopciones")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BotonJugar.setText(_translate("MainWindow", "Jugar"))
        self.BotonPuntuacion.setText(_translate("MainWindow", "Puntuaciones"))
        self.botonopciones.setText(_translate("MainWindow", "Opciones"))
    
    
   


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
