from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import numpy as np
import pandas as pd
from PyQt5.QtWidgets import QApplication, QMainWindow
from PyQt5.uic import loadUi

class Game(QMainWindow):
    def __init__(self):
        super().__init__()
        loadUi('game.ui', self)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1083, 948)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BotonAceptar = QtWidgets.QPushButton(self.centralwidget)
        self.BotonAceptar.setGeometry(QtCore.QRect(460, 880, 141, 41))
        self.BotonAceptar.setObjectName("BotonAceptar")
        self.BotonStart = QtWidgets.QPushButton(self.centralwidget)
        self.BotonStart.setGeometry(QtCore.QRect(460, 680, 141, 41))
        self.BotonStart.setObjectName("BotonStart")
        self.spacbackground = QtWidgets.QLabel(self.centralwidget)
        self.spacbackground.setGeometry(QtCore.QRect(0, 0, 1081, 471))
        self.spacbackground.setText("")
        self.spacbackground.setPixmap(QtGui.QPixmap("img/space1.jpg"))
        self.spacbackground.setScaledContents(True)
        self.spacbackground.setObjectName("spacbackground")
        self.ShipIcon = QtWidgets.QLabel(self.centralwidget)
        self.ShipIcon.setGeometry(QtCore.QRect(30, 300, 191, 91))
        self.ShipIcon.setText("")
        self.ShipIcon.setPixmap(QtGui.QPixmap("img/SpShip.png"))
        self.ShipIcon.setScaledContents(True)
        self.ShipIcon.setObjectName("ShipIcon")
        self.EnemyShip = QtWidgets.QLabel(self.centralwidget)
        self.EnemyShip.setGeometry(QtCore.QRect(810, 280, 211, 131))
        self.EnemyShip.setText("")
        self.EnemyShip.setPixmap(QtGui.QPixmap("img/enemy.png"))
        self.EnemyShip.setScaledContents(True)
        self.EnemyShip.setObjectName("EnemyShip")
        self.hearts = QtWidgets.QLabel(self.centralwidget)
        self.hearts.setGeometry(QtCore.QRect(20, 20, 61, 51))
        self.hearts.setText("")
        self.hearts.setPixmap(QtGui.QPixmap("img/Heart.png"))
        self.hearts.setScaledContents(True)
        self.hearts.setObjectName("hearts")
        self.liveslabel = QtWidgets.QLabel(self.centralwidget)
        self.liveslabel.setGeometry(QtCore.QRect(80, 20, 41, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.liveslabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.liveslabel.setFont(font)
        self.liveslabel.setScaledContents(False)
        self.liveslabel.setObjectName("liveslabel")
        self.backgroundpregunta = QtWidgets.QLabel(self.centralwidget)
        self.backgroundpregunta.setGeometry(QtCore.QRect(0, 420, 1081, 141))
        self.backgroundpregunta.setText("")
        self.backgroundpregunta.setPixmap(QtGui.QPixmap("img/metalscreen.png"))
        self.backgroundpregunta.setScaledContents(True)
        self.backgroundpregunta.setObjectName("backgroundpregunta")
        self.labelpregunta = QtWidgets.QLabel(self.centralwidget)
        self.labelpregunta.setGeometry(QtCore.QRect(60, 450, 961, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.labelpregunta.setPalette(palette)
        self.labelpregunta.setText("")
        self.labelpregunta.setAlignment(QtCore.Qt.AlignCenter)
        self.labelpregunta.setObjectName("labelpregunta")
        self.RB1 = QtWidgets.QRadioButton(self.centralwidget)
        self.RB1.setGeometry(QtCore.QRect(10, 570, 1061, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.RB1.setPalette(palette)
        self.RB1.setObjectName("RB1")
        self.RB2 = QtWidgets.QRadioButton(self.centralwidget)
        self.RB2.setGeometry(QtCore.QRect(10, 650, 1071, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.RB2.setPalette(palette)
        self.RB2.setObjectName("RB2")
        self.RB3 = QtWidgets.QRadioButton(self.centralwidget)
        self.RB3.setGeometry(QtCore.QRect(10, 740, 1061, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.RB3.setPalette(palette)
        self.RB3.setObjectName("RB3")
        self.RB4 = QtWidgets.QRadioButton(self.centralwidget)
        self.RB4.setGeometry(QtCore.QRect(10, 800, 1061, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.RB4.setPalette(palette)
        self.RB4.setObjectName("RB4")
        self.spacbackground.raise_()
        self.ShipIcon.raise_()
        self.EnemyShip.raise_()
        self.hearts.raise_()
        self.liveslabel.raise_()
        self.backgroundpregunta.raise_()
        self.labelpregunta.raise_()
        self.RB3.raise_()
        self.RB4.raise_()
        self.RB2.raise_()
        self.BotonAceptar.raise_()
        self.BotonStart.raise_()
        self.RB1.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.BotonAceptar.hide()
        self.RB1.hide()
        self.RB2.hide()
        self.RB3.hide()
        self.RB4.hide()
        self.retranslateUi(MainWindow)
        game.reset_question()
        
        self.archivopreg = 'QyA.xlsx'
        self.preguntas = pd.read_excel(self.archivopreg)
        self.lives = 3
        self.score = 0
        self.used = []
        
        self.startButton.clicked.connect(self.start_game)
        self.BotonAceptar.clicked.connect(self.submit_answer)
        
    def start_game(self):
        self.reset_question()
        self.update_lives_label()
        self.score = 0
        self.used = []
        self.play_round()
        
    def play_round(self):
        if self.lives > 0:
            tam = len(self.preguntas)
            num = np.random.randint(0, tam)
            
            self.reset_question()
            
            if num not in self.used:
                self.used.append(num)
                print(self.used)
                
                pregunta = self.preguntas['Pregunta'][num]
                self.labelpregunta.setText(pregunta)
                respuestas = [
                    self.preguntas['A'][num],
                    self.preguntas['B'][num],
                    self.preguntas['C'][num],
                    self.preguntas['D'][num]
                ]
                self.RB1.setText(respuestas[0])
                self.RB2.setText(respuestas[1])
                self.RB3.setText(respuestas[2])
                self.RB4.setText(respuestas[3])
                
                respcorrecta = self.preguntas['Correcta'][num]
                
                self.BotonAceptar.setEnabled(True)  # Habilitar el botón para enviar la respuesta
                
                self.BotonAceptar.clicked.connect(
                    lambda: self.check_answer(respcorrecta.lower())
                )
            else:
                self.play_round()
        else:
            self.game_over()
        
    def check_answer(self, respcorrecta):
        answer = self.sender().text().lower()
        
        if answer == respcorrecta:
            self.score += 100
        else:
            self.lives -= 1
        
        self.update_lives_label()
        print("Score:", self.score)
        print("Lives:", self.lives)
        
        self.BotonAceptar.setEnabled(False)  # Deshabilitar el botón después de enviar la respuesta
        self.play_round()
        
    def reset_question(self):
        self.labelpregunta.clear()
        self.RB1.setText('')
        self.RB2.setText('')
        self.RB3.setText('')
        self.RB4.setText('')
        
    def update_lives_label(self):
        self.liveslabel.setText(str(self.lives))
        
    def game_over(self):
        print("Game Over")
        print("Final Score:", self.score)
        sys.exit()


if __name__ == "__main__":
    app = QApplication(sys.argv)
    game = Game()
    game.show()
    sys.exit(app.exec_())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    game = Game()
    game.setup(MainWindow)
    MainWindow.show()
    game.reset_question()
    sys.exit(app.exec_())
